-- =============================================================================
-- RoundLab — Add Drill Time Limit
-- Migration: 20260606000000_add_drill_time_limit.sql
--
-- Adds time_limit_seconds to drills table. Value is generated by the LLM
-- during drill generation (30–300s range, clamped in application code).
-- Older drills without this field show a heuristic fallback on the frontend.
--
-- Apply via: Supabase Dashboard → SQL Editor → paste and run.
-- Or via CLI: supabase db push (once project is linked).
-- =============================================================================

ALTER TABLE public.drills
  ADD COLUMN IF NOT EXISTS time_limit_seconds integer
    CHECK (time_limit_seconds IS NULL OR time_limit_seconds BETWEEN 30 AND 300);

COMMENT ON COLUMN public.drills.time_limit_seconds
  IS 'LLM-suggested practice time in seconds (30–300). NULL for drills generated before this migration.';
